import type { StarterCandidate } from './candidate';

/**
 * Activités, au sens large : loisirs créatifs, jeux, écrans et pop culture,
 * sorties, sports, voyages et expériences, et quelques rendez-vous nommés.
 * Sans sous-titre.
 */
export const ACTIVITIES: readonly StarterCandidate[] = [
  'Dessin',
  'Peinture',
  'Poterie',
  'Photographie',
  'Tricot',
  'Crochet',
  'Couture',
  'Origami',
  'Lego',
  'Puzzle',
  'Calligraphie',
  'Jardinage',
  'Cuisine',
  'Pâtisserie',
  'Bricolage',
  'Peinture de figurines',
  'Écriture',
  'Lecture',
  'Jeux de société',
  'Jeu de rôle sur table',
  'Échecs',
  'Poker',
  'Blind test',
  'Quiz en bar',
  'Escape game',
  'Murder party',
  'Loup-garou',
  'Karaoké',
  'Jeux vidéo',
  'LAN party',
  'Speedrun',
  'Jeu de cartes à collectionner',
  'Marathon de films',
  'Marathon de séries',
  'Cinéma en plein air',
  'Cosplay',
  'Streaming',
  'Écouter des podcasts',
  'Collection de figurines',
  'Chiner des vinyles',
  'Concert',
  'Festival de musique',
  'Cinéma',
  'Théâtre',
  'Stand-up',
  'Comédie musicale',
  'Musée',
  "Parc d'attractions",
  'Zoo',
  'Aquarium',
  'Bowling',
  'Laser game',
  "Salle d'arcade",
  'Karting',
  'Billard',
  'Brunch',
  'Apéro entre amis',
  'Pique-nique',
  'Barbecue',
  'Brocante',
  'Marché de Noël',
  'Football',
  'Basket-ball',
  'Tennis',
  'Badminton',
  'Ping-pong',
  'Pétanque',
  'Mölkky',
  'Natation',
  'Course à pied',
  'Vélo',
  'Randonnée',
  'Escalade',
  'Yoga',
  'Musculation',
  'Boxe',
  'Judo',
  'Danse',
  'Skateboard',
  'Roller',
  'Surf',
  'Ski',
  'Snowboard',
  'Patin à glace',
  'Plongée',
  'Équitation',
  'Paintball',
  'Accrobranche',
  'Canoë-kayak',
  'Parapente',
  'Saut en parachute',
  'Pêche',
  'Road trip',
  'Camping',
  'Croisière',
  'Observation des étoiles',
  'Montgolfière',
  'Géocaching',
  'Chasse aux trésors',
  'Spa',
  'Sieste',
  'Méditation',
  'Bénévolat',
  'Japan Expo',
  'Paris Games Week',
  'Z Event',
  'Fête de la musique',
  "Festival d'Angoulême",
  "Festival d'Annecy",
  'Hellfest',
  'Jeux olympiques',
].map((title) => ({ title }));
