import type { StarterCandidate } from './candidate';

/**
 * Livres, au sens large : classiques, fantasy et science-fiction, jeunesse,
 * romans d'aujourd'hui, essais, bandes dessinées, mangas et comics. Une série
 * entre sous son titre de série. Sous-titre : l'auteur, ou les auteurs.
 */
export const BOOKS: readonly StarterCandidate[] = [
  { title: 'Le Petit Prince', subtitle: 'Antoine de Saint-Exupéry' },
  { title: 'Les Misérables', subtitle: 'Victor Hugo' },
  { title: 'Notre-Dame de Paris', subtitle: 'Victor Hugo' },
  { title: 'Le Comte de Monte-Cristo', subtitle: 'Alexandre Dumas' },
  { title: 'Les Trois Mousquetaires', subtitle: 'Alexandre Dumas' },
  { title: 'Vingt mille lieues sous les mers', subtitle: 'Jules Verne' },
  { title: 'Le Tour du monde en quatre-vingts jours', subtitle: 'Jules Verne' },
  { title: "L'Étranger", subtitle: 'Albert Camus' },
  { title: 'Madame Bovary', subtitle: 'Gustave Flaubert' },
  { title: 'Germinal', subtitle: 'Émile Zola' },
  { title: 'Candide', subtitle: 'Voltaire' },
  { title: 'Cyrano de Bergerac', subtitle: 'Edmond Rostand' },
  { title: 'Les Fleurs du mal', subtitle: 'Charles Baudelaire' },
  { title: 'Orgueil et Préjugés', subtitle: 'Jane Austen' },
  { title: 'Frankenstein', subtitle: 'Mary Shelley' },
  { title: 'Dracula', subtitle: 'Bram Stoker' },
  { title: '1984', subtitle: 'George Orwell' },
  { title: 'La Ferme des animaux', subtitle: 'George Orwell' },
  { title: 'Le Meilleur des mondes', subtitle: 'Aldous Huxley' },
  { title: 'Fahrenheit 451', subtitle: 'Ray Bradbury' },
  { title: 'Des souris et des hommes', subtitle: 'John Steinbeck' },
  { title: 'Alice au pays des merveilles', subtitle: 'Lewis Carroll' },
  { title: 'Le Seigneur des anneaux', subtitle: 'J. R. R. Tolkien' },
  { title: 'Le Hobbit', subtitle: 'J. R. R. Tolkien' },
  { title: "Harry Potter à l'école des sorciers", subtitle: 'J. K. Rowling' },
  { title: 'Le Trône de fer', subtitle: 'George R. R. Martin' },
  { title: 'Dune', subtitle: 'Frank Herbert' },
  { title: 'Fondation', subtitle: 'Isaac Asimov' },
  { title: 'Le Guide du voyageur galactique', subtitle: 'Douglas Adams' },
  { title: 'La Horde du Contrevent', subtitle: 'Alain Damasio' },
  { title: 'Hunger Games', subtitle: 'Suzanne Collins' },
  { title: 'À la croisée des mondes', subtitle: 'Philip Pullman' },
  { title: 'Le Monde de Narnia', subtitle: 'C. S. Lewis' },
  { title: 'La Passe-miroir', subtitle: 'Christelle Dabos' },
  { title: 'Twilight', subtitle: 'Stephenie Meyer' },
  { title: 'Eragon', subtitle: 'Christopher Paolini' },
  { title: 'Le Problème à trois corps', subtitle: 'Liu Cixin' },
  { title: 'La Nuit des temps', subtitle: 'René Barjavel' },
  { title: 'Matilda', subtitle: 'Roald Dahl' },
  { title: 'Le Petit Nicolas', subtitle: 'René Goscinny et Jean-Jacques Sempé' },
  { title: 'Da Vinci Code', subtitle: 'Dan Brown' },
  { title: 'Millénium', subtitle: 'Stieg Larsson' },
  { title: 'Ça', subtitle: 'Stephen King' },
  { title: 'Shining', subtitle: 'Stephen King' },
  { title: 'La Ligne verte', subtitle: 'Stephen King' },
  { title: 'Les Apparences', subtitle: 'Gillian Flynn' },
  { title: 'Le Silence des agneaux', subtitle: 'Thomas Harris' },
  { title: "La Vérité sur l'affaire Harry Quebert", subtitle: 'Joël Dicker' },
  { title: 'Les Piliers de la Terre', subtitle: 'Ken Follett' },
  { title: "L'Alchimiste", subtitle: 'Paulo Coelho' },
  { title: 'Le Parfum', subtitle: 'Patrick Süskind' },
  { title: 'Cinquante nuances de Grey', subtitle: 'E. L. James' },
  { title: "L'Élégance du hérisson", subtitle: 'Muriel Barbery' },
  { title: "Changer l'eau des fleurs", subtitle: 'Valérie Perrin' },
  { title: "L'Amie prodigieuse", subtitle: 'Elena Ferrante' },
  { title: 'Kafka sur le rivage', subtitle: 'Haruki Murakami' },
  { title: 'La Servante écarlate', subtitle: 'Margaret Atwood' },
  { title: 'Sapiens', subtitle: 'Yuval Noah Harari' },
  { title: 'Les Quatre Accords toltèques', subtitle: 'Miguel Ruiz' },
  { title: 'Nos étoiles contraires', subtitle: 'John Green' },
  { title: 'Astérix', subtitle: 'René Goscinny et Albert Uderzo' },
  { title: 'Les Aventures de Tintin', subtitle: 'Hergé' },
  { title: 'Lucky Luke', subtitle: 'Morris' },
  { title: 'Gaston Lagaffe', subtitle: 'André Franquin' },
  { title: 'Les Schtroumpfs', subtitle: 'Peyo' },
  { title: 'Blake et Mortimer', subtitle: 'Edgar P. Jacobs' },
  { title: 'Largo Winch', subtitle: 'Jean Van Hamme et Philippe Francq' },
  { title: 'XIII', subtitle: 'Jean Van Hamme et William Vance' },
  { title: 'Thorgal', subtitle: 'Jean Van Hamme et Grzegorz Rosiński' },
  { title: 'Lanfeust de Troy', subtitle: 'Christophe Arleston et Didier Tarquin' },
  { title: 'Titeuf', subtitle: 'Zep' },
  { title: 'Boule et Bill', subtitle: 'Jean Roba' },
  { title: 'Le Chat', subtitle: 'Philippe Geluck' },
  { title: 'Blacksad', subtitle: 'Juan Díaz Canales et Juanjo Guarnido' },
  { title: 'Persépolis', subtitle: 'Marjane Satrapi' },
  { title: "L'Arabe du futur", subtitle: 'Riad Sattouf' },
  { title: 'Mortelle Adèle', subtitle: 'Mr Tan' },
  { title: 'Les Vieux Fourneaux', subtitle: 'Wilfrid Lupano et Paul Cauuet' },
  { title: 'One Piece', subtitle: 'Eiichiro Oda' },
  { title: 'Naruto', subtitle: 'Masashi Kishimoto' },
  { title: 'Dragon Ball', subtitle: 'Akira Toriyama' },
  { title: 'Death Note', subtitle: 'Tsugumi Ohba et Takeshi Obata' },
  { title: "L'Attaque des Titans", subtitle: 'Hajime Isayama' },
  { title: 'Fullmetal Alchemist', subtitle: 'Hiromu Arakawa' },
  { title: 'Hunter × Hunter', subtitle: 'Yoshihiro Togashi' },
  { title: 'Berserk', subtitle: 'Kentaro Miura' },
  { title: 'Jujutsu Kaisen', subtitle: 'Gege Akutami' },
  { title: 'Demon Slayer', subtitle: 'Koyoharu Gotouge' },
  { title: 'My Hero Academia', subtitle: 'Kohei Horikoshi' },
  { title: 'Chainsaw Man', subtitle: 'Tatsuki Fujimoto' },
  { title: 'Spy×Family', subtitle: 'Tatsuya Endo' },
  { title: 'Vagabond', subtitle: 'Takehiko Inoue' },
  { title: 'Slam Dunk', subtitle: 'Takehiko Inoue' },
  { title: 'Akira', subtitle: 'Katsuhiro Otomo' },
  { title: "JoJo's Bizarre Adventure", subtitle: 'Hirohiko Araki' },
  { title: 'One-Punch Man', subtitle: 'ONE et Yusuke Murata' },
  { title: 'Frieren', subtitle: 'Kanehito Yamada et Tsukasa Abe' },
  { title: 'Vinland Saga', subtitle: 'Makoto Yukimura' },
  { title: 'Monster', subtitle: 'Naoki Urasawa' },
  { title: 'Nana', subtitle: 'Ai Yazawa' },
  { title: 'Détective Conan', subtitle: 'Gosho Aoyama' },
  { title: 'Solo Leveling', subtitle: 'Chugong' },
  { title: 'Watchmen', subtitle: 'Alan Moore et Dave Gibbons' },
  { title: 'Batman : The Dark Knight Returns', subtitle: 'Frank Miller' },
  { title: 'The Walking Dead', subtitle: 'Robert Kirkman et Charlie Adlard' },
  { title: 'Sandman', subtitle: 'Neil Gaiman' },
  { title: 'V pour Vendetta', subtitle: 'Alan Moore et David Lloyd' },
  { title: 'Scott Pilgrim', subtitle: "Bryan Lee O'Malley" },
  { title: 'Maus', subtitle: 'Art Spiegelman' },
  { title: 'Invincible', subtitle: 'Robert Kirkman et Cory Walker' },
];
