import type { StarterCandidate } from './candidate';

/**
 * Plats, au sens large : cuisine française et régionale, cuisines du monde,
 * street food, desserts, viennoiseries et goûters cultes. Sans sous-titre :
 * l'origine d'un plat est souvent discutée.
 */
export const DISHES: readonly StarterCandidate[] = [
  'Raclette',
  'Tartiflette',
  'Fondue savoyarde',
  'Bœuf bourguignon',
  'Blanquette de veau',
  'Pot-au-feu',
  'Coq au vin',
  'Cassoulet',
  'Choucroute',
  'Gratin dauphinois',
  'Hachis parmentier',
  'Croque-monsieur',
  'Quiche lorraine',
  'Ratatouille',
  'Bouillabaisse',
  'Moules-frites',
  'Steak-frites',
  'Poulet rôti',
  'Galette complète',
  "Soupe à l'oignon",
  'Aligot',
  'Tartare de bœuf',
  'Magret de canard',
  'Escargots de Bourgogne',
  'Salade niçoise',
  'Œufs mimosa',
  'Coquillettes au jambon',
  'Endives au jambon',
  'Tarte flambée',
  'Brandade de morue',
  'Pizza margherita',
  'Pizza hawaïenne',
  'Lasagnes',
  'Spaghetti carbonara',
  'Spaghetti bolognaise',
  'Risotto',
  'Gnocchis',
  'Burger',
  'Tacos',
  'Burrito',
  'Chili con carne',
  'Paella',
  'Sushi',
  'Ramen',
  'Udon',
  'Onigiri',
  'Gyoza',
  'Takoyaki',
  'Okonomiyaki',
  'Curry japonais',
  'Tempura',
  'Bento',
  'Bibimbap',
  'Poulet frit coréen',
  'Pad thaï',
  'Phở',
  'Bò bún',
  'Nems',
  'Canard laqué',
  'Dim sum',
  'Riz cantonais',
  'Butter chicken',
  'Couscous',
  'Tajine',
  'Falafel',
  'Houmous',
  'Moussaka',
  'Mafé',
  'Fish and chips',
  'Poke bowl',
  'Kebab',
  'French tacos',
  'Hot-dog',
  'Sandwich jambon-beurre',
  'Panini',
  'Frites',
  'Nuggets',
  'Nachos',
  'Bagel',
  'Pop-corn',
  'Barbe à papa',
  'Tiramisu',
  'Mousse au chocolat',
  'Crème brûlée',
  'Fondant au chocolat',
  'Tarte Tatin',
  'Tarte au citron meringuée',
  'Île flottante',
  'Profiteroles',
  'Éclair au chocolat',
  'Paris-Brest',
  'Mille-feuille',
  'Macaron',
  'Crêpe',
  'Gaufre',
  'Cheesecake',
  'Cookie',
  'Brownie',
  'Pancakes',
  'Donut',
  'Churros',
  'Mochi',
  'Riz au lait',
  'Clafoutis',
  'Galette des rois',
  'Bûche de Noël',
  'Croissant',
  'Pain au chocolat',
  'Pain perdu',
  'Chouquettes',
  'Madeleine',
  'Dorayaki',
  'Nutella',
  'Kinder Bueno',
  'Fraise Tagada',
].map((title) => ({ title }));
