import type { StarterCandidate } from './candidate';

/**
 * Jeux vidéo : classiques et récents, toutes plateformes et tous genres, des
 * grandes licences aux jeux indépendants. Sous-titre : le studio de
 * développement, laissé vide quand il prête à discussion.
 */
export const VIDEO_GAMES: readonly StarterCandidate[] = [
  { title: 'Super Mario Bros.', subtitle: 'Nintendo' },
  { title: 'Super Mario 64', subtitle: 'Nintendo' },
  { title: 'Super Mario Odyssey', subtitle: 'Nintendo' },
  { title: 'Super Mario Bros. Wonder', subtitle: 'Nintendo' },
  { title: 'Mario Kart 8 Deluxe', subtitle: 'Nintendo' },
  { title: 'Mario Kart World', subtitle: 'Nintendo' },
  { title: 'Super Smash Bros. Ultimate', subtitle: 'Bandai Namco Studios et Sora Ltd.' },
  { title: 'The Legend of Zelda: Ocarina of Time', subtitle: 'Nintendo' },
  { title: 'The Legend of Zelda: Breath of the Wild', subtitle: 'Nintendo' },
  { title: 'The Legend of Zelda: Tears of the Kingdom', subtitle: 'Nintendo' },
  { title: 'Animal Crossing: New Horizons', subtitle: 'Nintendo' },
  { title: 'Donkey Kong Bananza', subtitle: 'Nintendo' },
  { title: 'Wii Sports', subtitle: 'Nintendo' },
  { title: 'Splatoon 3', subtitle: 'Nintendo' },
  { title: 'Kirby et le monde oublié', subtitle: 'HAL Laboratory' },
  { title: 'Donkey Kong Country', subtitle: 'Rare' },
  { title: 'GoldenEye 007', subtitle: 'Rare' },
  { title: 'Pokémon Rouge et Bleu', subtitle: 'Game Freak' },
  { title: 'Pokémon Écarlate et Violet', subtitle: 'Game Freak' },
  { title: 'Légendes Pokémon : Z-A', subtitle: 'Game Freak' },
  { title: 'Pokémon GO', subtitle: 'Niantic' },
  { title: "Professeur Layton et l'Étrange Village", subtitle: 'Level-5' },
  { title: 'Tetris' },
  { title: 'Pac-Man', subtitle: 'Namco' },
  { title: 'Street Fighter II', subtitle: 'Capcom' },
  { title: 'Street Fighter 6', subtitle: 'Capcom' },
  { title: 'Mortal Kombat', subtitle: 'Midway' },
  { title: 'Tekken 3', subtitle: 'Namco' },
  { title: 'Resident Evil 4', subtitle: 'Capcom' },
  { title: 'Monster Hunter Wilds', subtitle: 'Capcom' },
  { title: 'Phoenix Wright: Ace Attorney', subtitle: 'Capcom' },
  { title: 'Final Fantasy VII', subtitle: 'Square' },
  { title: 'Final Fantasy X', subtitle: 'Square' },
  { title: 'Kingdom Hearts', subtitle: 'Square' },
  { title: 'NieR: Automata', subtitle: 'PlatinumGames' },
  { title: 'Metal Gear Solid', subtitle: 'Konami' },
  { title: 'Silent Hill 2', subtitle: 'Konami' },
  { title: 'Sonic the Hedgehog', subtitle: 'Sonic Team' },
  { title: 'Yakuza 0', subtitle: 'Ryu Ga Gotoku Studio' },
  { title: 'Persona 5', subtitle: 'Atlus' },
  { title: 'Dragon Ball: Sparking! Zero', subtitle: 'Spike Chunsoft' },
  { title: 'Elden Ring', subtitle: 'FromSoftware' },
  { title: 'Dark Souls', subtitle: 'FromSoftware' },
  { title: 'Bloodborne', subtitle: 'FromSoftware' },
  { title: 'Ghost of Tsushima', subtitle: 'Sucker Punch Productions' },
  { title: 'Ghost of Yōtei', subtitle: 'Sucker Punch Productions' },
  { title: 'The Last of Us', subtitle: 'Naughty Dog' },
  { title: 'Uncharted 2: Among Thieves', subtitle: 'Naughty Dog' },
  { title: 'Crash Bandicoot', subtitle: 'Naughty Dog' },
  { title: 'God of War', subtitle: 'Santa Monica Studio' },
  { title: 'Horizon Zero Dawn', subtitle: 'Guerrilla Games' },
  { title: "Marvel's Spider-Man", subtitle: 'Insomniac Games' },
  { title: 'Astro Bot', subtitle: 'Team Asobi' },
  { title: 'Shadow of the Colossus', subtitle: 'Team Ico' },
  { title: 'Journey', subtitle: 'thatgamecompany' },
  { title: 'Death Stranding', subtitle: 'Kojima Productions' },
  { title: 'Gran Turismo', subtitle: 'Polyphony Digital' },
  { title: 'Grand Theft Auto V', subtitle: 'Rockstar North' },
  { title: 'Red Dead Redemption 2', subtitle: 'Rockstar Games' },
  { title: 'Halo: Combat Evolved', subtitle: 'Bungie' },
  { title: 'Fortnite', subtitle: 'Epic Games' },
  { title: 'Minecraft', subtitle: 'Mojang Studios' },
  { title: 'Roblox', subtitle: 'Roblox Corporation' },
  { title: 'Forza Horizon 5', subtitle: 'Playground Games' },
  { title: 'The Elder Scrolls V: Skyrim', subtitle: 'Bethesda Game Studios' },
  { title: "Baldur's Gate 3", subtitle: 'Larian Studios' },
  { title: 'The Witcher 3: Wild Hunt', subtitle: 'CD Projekt Red' },
  { title: 'Cyberpunk 2077', subtitle: 'CD Projekt Red' },
  { title: 'World of Warcraft', subtitle: 'Blizzard Entertainment' },
  { title: 'Overwatch', subtitle: 'Blizzard Entertainment' },
  { title: 'League of Legends', subtitle: 'Riot Games' },
  { title: 'Valorant', subtitle: 'Riot Games' },
  { title: 'Counter-Strike 2', subtitle: 'Valve' },
  { title: 'Half-Life 2', subtitle: 'Valve' },
  { title: 'Portal 2', subtitle: 'Valve' },
  { title: 'Rocket League', subtitle: 'Psyonix' },
  { title: 'Call of Duty 4: Modern Warfare', subtitle: 'Infinity Ward' },
  { title: 'Les Sims', subtitle: 'Maxis' },
  { title: 'Age of Empires II', subtitle: 'Ensemble Studios' },
  { title: "Assassin's Creed II", subtitle: 'Ubisoft Montréal' },
  { title: 'Prince of Persia : Les Sables du temps', subtitle: 'Ubisoft Montréal' },
  { title: 'Rayman Legends', subtitle: 'Ubisoft Montpellier' },
  { title: 'Just Dance', subtitle: 'Ubisoft Paris' },
  { title: 'Detroit: Become Human', subtitle: 'Quantic Dream' },
  { title: 'Life is Strange', subtitle: 'Dontnod Entertainment' },
  { title: 'Clair Obscur : Expedition 33', subtitle: 'Sandfall Interactive' },
  { title: 'A Plague Tale: Innocence', subtitle: 'Asobo Studio' },
  { title: 'Dishonored', subtitle: 'Arkane Studios' },
  { title: 'Dead Cells', subtitle: 'Motion Twin' },
  { title: 'Hollow Knight', subtitle: 'Team Cherry' },
  { title: 'Hollow Knight: Silksong', subtitle: 'Team Cherry' },
  { title: 'Celeste' },
  { title: 'Stardew Valley', subtitle: 'ConcernedApe' },
  { title: 'Undertale', subtitle: 'Toby Fox' },
  { title: 'Hades', subtitle: 'Supergiant Games' },
  { title: 'Cuphead', subtitle: 'Studio MDHR' },
  { title: 'Among Us', subtitle: 'Innersloth' },
  { title: 'Terraria', subtitle: 'Re-Logic' },
  { title: 'Outer Wilds', subtitle: 'Mobius Digital' },
  { title: 'Balatro', subtitle: 'LocalThunk' },
  { title: 'It Takes Two', subtitle: 'Hazelight Studios' },
  { title: 'Genshin Impact', subtitle: 'miHoYo' },
  { title: 'Clash of Clans', subtitle: 'Supercell' },
  { title: 'Candy Crush Saga', subtitle: 'King' },
  { title: 'Tomb Raider', subtitle: 'Core Design' },
  { title: 'Doom', subtitle: 'id Software' },
  { title: 'Lego Star Wars : La Saga complète', subtitle: "Traveller's Tales" },
  { title: 'The Secret of Monkey Island', subtitle: 'Lucasfilm Games' },
  { title: 'Black Myth: Wukong', subtitle: 'Game Science' },
  { title: 'Lethal Company', subtitle: 'Zeekerss' },
];
